unique_ids:
  assets:
    standard-page.html: MOQU5CNXR72FZXPPGKPFI2S4OTTSOZCV
    theme.css: RFZM7V4E4NMEIC6EDFMLPMWLH4JVAV5N
  forms:
    Form1: 2GFYKNLZWE6YVV5LM656V4UTRYLQYO3R
  modules: {}
  scripts: {}
  server_modules: {}
